on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1

      with:
          java-version: 1.8

      uses: eskatos/gradle-command-action@v1.3.2
      with:
        gradle-version: wrapper
        arguments: build --stacktrace

      uses: eskatos/gradle-command-action@v1.3.2
      with:
        gradle-version: wrapper
        arguments: :wheel:bintrayUpload --stacktrace
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
